### ISSUE TITLE
Segfault on debian

### ISSUE THREAD

**Issue by K4ST0R** [php-rdkafka/php-rdkafka#16]
Hello,
I have a bug with PHP 5.5.30-1~dotdeb+7.1, kafka_2.10-0.8.2.2.
When I use the library I have a segfault when I use this function : 

"$topic->produce(RD_KAFKA_PARTITION_UA, 0, serialize($argument));"

Here my code : 
$topic_name = 'task_open';
$rk = new RdKafka\Producer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("localhost");
$topic = $rk->newTopic($topic_name);
$topic->produce(RD_KAFKA_PARTITION_UA, 0, serialize($argument));

Thank you,

**Comment by arnaud-lb** [comment]
Hello @K4ST0R,

Could you generate a stack trace for this ? https://bugs.php.net/bugs-generating-backtrace.php

**Comment by K4ST0R** [comment]
Of course,

```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f2dbac94dea in rd_kafka_toppar_get (rkt=rkt@entry=0x0, partition=partition@entry=0,
    ua_on_miss=ua_on_miss@entry=0) at rdkafka_partition.c:229
229             if (partition >= 0 && partition < rkt->rkt_partition_cnt)
(gdb) bt
#0  0x00007f2dbac94dea in rd_kafka_toppar_get (rkt=rkt@entry=0x0, partition=partition@entry=0,
    ua_on_miss=ua_on_miss@entry=0) at rdkafka_partition.c:229
#1  0x00007f2dbac7b82f in rd_kafka_topic_partition_available (app_rkt=app_rkt@entry=0x0,
    partition=partition@entry=0) at rdkafka_topic.c:931
#2  0x00007f2dbac79080 in rd_kafka_msg_partitioner_random (rkt=0x0, key=<optimized out>,
    keylen=<optimized out>, partition_cnt=1, rkt_opaque=<optimized out>, msg_opaque=<optimized out>)
    at rdkafka_msg.c:328
#3  0x00007f2dbac792c6 in rd_kafka_msg_partitioner (rkt=rkt@entry=0x2b28900,
    rkm=rkm@entry=0x7f2db0000eb0, do_lock=do_lock@entry=0) at rdkafka_msg.c:388
#4  0x00007f2dbac79ead in rd_kafka_topic_assign_uas (rkt=rkt@entry=0x2b28900) at rdkafka_topic.c:561
#5  0x00007f2dbac7aef1 in rd_kafka_topic_metadata_update (rkb=rkb@entry=0x2b28100,
    mdt=mdt@entry=0x2b29fd5) at rdkafka_topic.c:753
#6  0x00007f2dbac87407 in rd_kafka_parse_Metadata (rkb=rkb@entry=0x2b28100, rkt=0x0,
    rkbuf=rkbuf@entry=0x2b29b50) at rdkafka_request.c:1575
#7  0x00007f2dbac8e948 in rd_kafka_op_handle_Metadata (rkb=0x2b28100, err=RD_KAFKA_RESP_ERR_NO_ERROR,
    rkbuf=0x2b29b50, request=<optimized out>, opaque=0x2b29760) at rdkafka_request.c:1636
#8  0x00007f2dbac82829 in rd_kafka_buf_callback (rkb=0x2b28100, err=RD_KAFKA_RESP_ERR_NO_ERROR,
    response=0x2b29b50, request=0x2b29980) at rdkafka_buf.c:468
#9  0x00007f2dbac65d59 in rd_kafka_toppar_q_cb (rk=<optimized out>, rko=<optimized out>,
    cb_type=<optimized out>, opaque=<optimized out>) at rdkafka.c:876
#10 0x00007f2dbac8460a in rd_kafka_q_serve (rkq=rkq@entry=0x2b25c30, timeout_ms=<optimized out>,
    max_cnt=max_cnt@entry=0, cb_type=cb_type@entry=0,
    callback=callback@entry=0x7f2dbac65d50 <rd_kafka_toppar_q_cb>, opaque=opaque@entry=0x0)
    at rdkafka_queue.c:364
#11 0x00007f2dbac6d125 in rd_kafka_toppars_q_serve (timeout_ms=<optimized out>, rkq=0x2b25c30)
    at rdkafka.c:882
#12 rd_kafka_thread_main (arg=arg@entry=0x2b25b70) at rdkafka.c:919
#13 0x00007f2dbac9cd5f in _thrd_wrapper_function (aArg=<optimized out>) at tinycthread.c:596
#14 0x00007f2dbc4c3b50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#15 0x00007f2dbc9ca95d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#16 0x0000000000000000 in ?? ()
```

**Comment by K4ST0R** [comment]
Hi mate,
have some news ?

**Comment by arnaud-lb** [comment]
Hi @K4ST0R,

I can't reproduce the issue here. Are you using any unusual compiler, libc, thread library ?

**Comment by arnaud-lb** [comment]
Hi @K4ST0R,

I've been able to reproduce the problem with librdkafka master. I doesn't crash with the 0.8.6 tag.

I'll investigate.

**Comment by arnaud-lb** [comment]
Related librdkafka bug: https://github.com/edenhill/librdkafka/issues/502

**Comment by edenhill** [comment]
Now fixed in librdkafka upstream (master)

**Comment by arnaud-lb** [comment]
Thanks @edenhill !

**Comment by K4ST0R** [comment]
Thanks a lot @edenhill and @arnaud-lb !
