### ISSUE TITLE
Failed to consume message

### ISSUE THREAD

**Issue by renzhenguo** [php-rdkafka/php-rdkafka#362]
* PHP version: 7.1.1
 * librdkafka version: 1.3.0
 * php-rdkafka version: 4.0.4-dev 
 * kafka version: 2.10

code

        $conf = new \RdKafka\Conf();

        // Set the group id. This is required when storing offsets on the broker
        $conf->set('group.id', 'dev_test2');
        $conf->set('log_level', '7');
        $conf->set('debug', 'all');

        $rk = new \RdKafka\Consumer($conf);
        $rk->addBrokers('10.0.0.181:9092,10.0.0.182:9092,10.0.0.183:9092');

        $topicConf = new \RdKafka\TopicConf();
        $topicConf->set('auto.commit.interval.ms', 100);

        // Set the offset store method to 'file'
        $topicConf->set('offset.store.method', 'broker');

        // Alternatively, set the offset store method to 'none'
        // $topicConf->set('offset.store.method', 'none');

        // Set where to start consuming messages when there is no initial offset in
        // offset store or the desired offset is out of range.
        // 'smallest': start from the beginning
        $topicConf->set('auto.offset.reset', 'smallest');

        $topic = $rk->newTopic("dsp1", $topicConf);

        // Start consuming partition 0
        $topic->consumeStart(0, RD_KAFKA_OFFSET_STORED);

        while (true) {
            $message = $topic->consume(0, 1000);
            var_dump($message);
            exit();
            echo "------------------------------start\n";
            switch ($message->err) {
            case RD_KAFKA_RESP_ERR_NO_ERROR:
                echo "ok\n";
                var_dump($message);
                break;
            case RD_KAFKA_RESP_ERR__PARTITION_EOF:
                echo "No more messages; will wait for more\n";
                break;
            case RD_KAFKA_RESP_ERR__TIMED_OUT:
                echo "Timed out\n";
                break;
            default:
                throw new \Exception($message->errstr(), $message->err);
                break;
            }
        }

log
%7|1584699821.531|MEMBERID|rdkafka#consumer-1| [thrd:app]: Group "dev_test2": updating member id "(not-set)" -> ""
%7|1584699821.531|WAKEUPFD|rdkafka#consumer-1| [thrd:app]: GroupCoordinator: Enabled low-latency ops queue wake-ups
%7|1584699821.531|BROKER|rdkafka#consumer-1| [thrd:app]: GroupCoordinator: Added new broker with NodeId -1
%7|1584699821.531|BRKMAIN|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Enter main broker thread
%7|1584699821.531|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v1.3.0 (0x10300ff) rdkafka#consumer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_plain,sasl_scram,plugins,sasl_oauthbearer, GCC GXX PKGCONFIG INSTALL GNULD LDS LIBDL PLUGINS ZLIB SSL HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0xfffff)
%7|1584699821.531|BRKMAIN|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1584699821.531|WAKEUPFD|rdkafka#consumer-1| [thrd:app]: 10.0.0.181:9092/bootstrap: Enabled low-latency ops queue wake-ups
%7|1584699821.531|BROKER|rdkafka#consumer-1| [thrd:app]: 10.0.0.181:9092/bootstrap: Added new broker with NodeId -1
%7|1584699821.531|WAKEUPFD|rdkafka#consumer-1| [thrd:app]: 10.0.0.182:9092/bootstrap: Enabled low-latency ops queue wake-ups
%7|1584699821.531|BRKMAIN|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Enter main broker thread
%7|1584699821.531|BROKER|rdkafka#consumer-1| [thrd:app]: 10.0.0.182:9092/bootstrap: Added new broker with NodeId -1
%7|1584699821.531|WAKEUPFD|rdkafka#consumer-1| [thrd:app]: 10.0.0.183:9092/bootstrap: Enabled low-latency ops queue wake-ups
%7|1584699821.531|BRKMAIN|rdkafka#consumer-1| [thrd:10.0.0.182:9092/bootstrap]: 10.0.0.182:9092/bootstrap: Enter main broker thread
%7|1584699821.531|BROKER|rdkafka#consumer-1| [thrd:app]: 10.0.0.183:9092/bootstrap: Added new broker with NodeId -1
%7|1584699821.531|BRKMAIN|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Enter main broker thread
%7|1584699821.531|TOPIC|rdkafka#consumer-1| [thrd:app]: New local topic: dsp1
%7|1584699821.531|TOPPARNEW|rdkafka#consumer-1| [thrd:app]: NEW dsp1 [-1] 0x1f75f10 (at rd_kafka_topic_new0:393)
%7|1584699821.531|CONNECT|rdkafka#consumer-1| [thrd:app]: 10.0.0.181:9092/bootstrap: Selected for cluster connection: leader query (broker has 0 connection attempt(s))
%7|1584699821.531|CONNECT|rdkafka#consumer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: leader query
%7|1584699821.531|METADATA|rdkafka#consumer-1| [thrd:app]: Skipping metadata refresh of 1 topic(s): no usable brokers
%7|1584699821.531|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Received CONNECT op
%7|1584699821.531|START|rdkafka#consumer-1| [thrd:app]: Start consuming partition 0
%7|1584699821.531|STATE|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1584699821.532|TOPPARNEW|rdkafka#consumer-1| [thrd:app]: NEW dsp1 [0] 0x1f76480 (at rd_kafka_toppar_desired_add:628)
%7|1584699821.532|DESIRED|rdkafka#consumer-1| [thrd:app]: dsp1 [0]: adding to DESIRED list
%7|1584699821.532|DESP|rdkafka#consumer-1| [thrd:app]: Adding desired topic dsp1 [0]
%7|1584699821.532|BROADCAST|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: Broadcasting state change
%7|1584699821.532|BARRIER|rdkafka#consumer-1| [thrd:app]: dsp1 [0]: rd_kafka_toppar_op_fetch_start:2298: new version barrier v2
%7|1584699821.532|CONSUMER|rdkafka#consumer-1| [thrd:app]: Start consuming dsp1 [0] at offset STORED (v2)
%7|1584699821.532|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1584699821.532|STATE|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1584699821.532|BROADCAST|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: Broadcasting state change
%7|1584699821.532|OP|rdkafka#consumer-1| [thrd:main]: dsp1 [0] received op FETCH_START (v2) in fetch-state none (opv1)
%7|1584699821.532|FETCH|rdkafka#consumer-1| [thrd:main]: Start fetch for dsp1 [0] in state none at offset STORED (v2)
%7|1584699821.532|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: using offset store method: broker
%7|1584699821.532|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition dsp1 [0] changed fetch state none -> offset-query
%7|1584699821.532|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: offset reset (at offset STORED) to STORED: query broker for offsets: Success
%7|1584699821.532|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: no current leader for partition: (re)starting offset query timer for offset STORED
%7|1584699821.532|CGRPSTATE|rdkafka#consumer-1| [thrd:main]: Group "dev_test2" changed state init -> query-coord (v1, join-state init)
%7|1584699821.532|BROADCAST|rdkafka#consumer-1| [thrd:main]: Broadcasting state change
%7|1584699821.532|CONNECT|rdkafka#consumer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: coordinator query
%7|1584699821.532|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: Group "dev_test2": no broker available for coordinator query: intervaled in state query-coord
%7|1584699821.532|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "dev_test2" received op PARTITION_JOIN in state query-coord (join state init, v1) for dsp1 [0]
%7|1584699821.532|PARTADD|rdkafka#consumer-1| [thrd:main]: Group "dev_test2": add dsp1 [0]
%7|1584699821.532|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Connecting to ipv4#10.0.0.181:9092 (plaintext) with socket 15
%7|1584699821.537|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Connected to ipv4#10.0.0.181:9092
%7|1584699821.537|CONNECTED|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Connected (#1)
%7|1584699821.537|FEATURE|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1584699821.537|STATE|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1584699821.537|BROADCAST|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: Broadcasting state change
%7|1584699821.537|SEND|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Sent ApiVersionRequest (v0, 25 bytes @ 0, CorrId 1)
%7|1584699821.542|BROKERFAIL|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
%7|1584699821.542|FEATURE|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Updated enabled protocol features -ApiVersion to 
%7|1584699821.542|STATE|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Broker changed state APIVERSION_QUERY -> DOWN
%7|1584699821.542|BROADCAST|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: Broadcasting state change
%7|1584699821.542|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Purging bufq with 1 buffers
%7|1584699821.542|BROKERFAIL|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
%7|1584699821.542|FAIL|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: ApiVersionRequest failed: Local: Broker transport failure: probably due to old broker version (after 0ms in state DOWN)
%7|1584699821.542|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Purging bufq with 0 buffers
%7|1584699821.542|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Purging bufq with 0 buffers
%7|1584699821.542|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Updating 0 buffers on connection reset
%7|1584699821.543|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Purging bufq with 0 buffers
%7|1584699821.543|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: 10.0.0.181:9092/bootstrap: Updating 0 buffers on connection reset
%7|1584699821.543|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: Not selecting any broker for cluster connection: still suppressed for 38ms: broker down
%7|1584699821.543|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: Not selecting any broker for cluster connection: still suppressed for 38ms: broker down
%7|1584699821.543|METADATA|rdkafka#consumer-1| [thrd:10.0.0.181:9092/bootstrap]: Skipping metadata refresh of 1 topic(s): no usable brokers
%7|1584699821.632|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: commit: stored offset -1001 > committed offset -1001?
%7|1584699821.732|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: commit: stored offset -1001 > committed offset -1001?
%7|1584699821.832|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: commit: stored offset -1001 > committed offset -1001?
%7|1584699821.932|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: commit: stored offset -1001 > committed offset -1001?
%7|1584699822.032|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic dsp1 [0]: timed offset query for STORED in state offset-query
%7|1584699822.032|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: no current leader for partition: (re)starting offset query timer for offset STORED
%7|1584699822.032|CONNECT|rdkafka#consumer-1| [thrd:main]: 10.0.0.183:9092/bootstrap: Selected for cluster connection: coordinator query (broker has 0 connection attempt(s))
%7|1584699822.032|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: Group "dev_test2": no broker available for coordinator query: intervaled in state query-coord
%7|1584699822.032|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Received CONNECT op
%7|1584699822.032|STATE|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1584699822.032|BROADCAST|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: Broadcasting state change
%7|1584699822.032|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: commit: stored offset -1001 > committed offset -1001?
%7|1584699822.032|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1584699822.032|STATE|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1584699822.032|BROADCAST|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: Broadcasting state change
%7|1584699822.032|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Connecting to ipv4#10.0.0.183:9092 (plaintext) with socket 15
%7|1584699822.038|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Connected to ipv4#10.0.0.183:9092
%7|1584699822.038|CONNECTED|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Connected (#1)
%7|1584699822.038|FEATURE|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1584699822.038|STATE|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1584699822.038|BROADCAST|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: Broadcasting state change
%7|1584699822.038|SEND|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Sent ApiVersionRequest (v0, 25 bytes @ 0, CorrId 1)
%7|1584699822.043|BROKERFAIL|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
%7|1584699822.043|FEATURE|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Updated enabled protocol features -ApiVersion to 
%7|1584699822.043|STATE|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Broker changed state APIVERSION_QUERY -> DOWN
%7|1584699822.043|BROADCAST|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: Broadcasting state change
%7|1584699822.043|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Purging bufq with 1 buffers
%7|1584699822.043|BROKERFAIL|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
%7|1584699822.043|FAIL|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: ApiVersionRequest failed: Local: Broker transport failure: probably due to old broker version (after 0ms in state DOWN)
%7|1584699822.043|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Purging bufq with 0 buffers
%7|1584699822.043|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Purging bufq with 0 buffers
%7|1584699822.043|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Updating 0 buffers on connection reset
%7|1584699822.043|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Purging bufq with 0 buffers
%7|1584699822.043|BUFQ|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: 10.0.0.183:9092/bootstrap: Updating 0 buffers on connection reset
%7|1584699822.043|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: Not selecting any broker for cluster connection: still suppressed for 38ms: broker down
%7|1584699822.043|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: Not selecting any broker for cluster connection: still suppressed for 38ms: broker down
%7|1584699822.043|METADATA|rdkafka#consumer-1| [thrd:10.0.0.183:9092/bootstrap]: Skipping metadata refresh of 1 topic(s): no usable brokers
%7|1584699822.132|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: commit: stored offset -1001 > committed offset -1001?
%7|1584699822.232|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: commit: stored offset -1001 > committed offset -1001?
%7|1584699822.332|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: commit: stored offset -1001 > committed offset -1001?
%7|1584699822.432|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: commit: stored offset -1001 > committed offset -1001?
%7|1584699822.531|NOINFO|rdkafka#consumer-1| [thrd:main]: Topic dsp1 metadata information unknown
%7|1584699822.531|NOINFO|rdkafka#consumer-1| [thrd:main]: Topic dsp1 partition count is zero: should refresh metadata
%7|1584699822.531|CONNECT|rdkafka#consumer-1| [thrd:main]: 10.0.0.182:9092/bootstrap: Selected for cluster connection: refresh unavailable topics (broker has 0 connection attempt(s))
%7|1584699822.531|CONNECT|rdkafka#consumer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics
%7|1584699822.531|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.182:9092/bootstrap]: 10.0.0.182:9092/bootstrap: Received CONNECT op
%7|1584699822.531|METADATA|rdkafka#consumer-1| [thrd:main]: Skipping metadata refresh of 1 topic(s): no usable brokers
%7|1584699822.531|STATE|rdkafka#consumer-1| [thrd:10.0.0.182:9092/bootstrap]: 10.0.0.182:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1584699822.531|CONNECT|rdkafka#consumer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection
%7|1584699822.531|BROADCAST|rdkafka#consumer-1| [thrd:10.0.0.182:9092/bootstrap]: Broadcasting state change
%7|1584699822.531|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.182:9092/bootstrap]: 10.0.0.182:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1584699822.531|STATE|rdkafka#consumer-1| [thrd:10.0.0.182:9092/bootstrap]: 10.0.0.182:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1584699822.531|BROADCAST|rdkafka#consumer-1| [thrd:10.0.0.182:9092/bootstrap]: Broadcasting state change
%7|1584699822.531|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.182:9092/bootstrap]: 10.0.0.182:9092/bootstrap: Connecting to ipv4#10.0.0.182:9092 (plaintext) with socket 15
NULL
%7|1584699822.532|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic dsp1 [0]: timed offset query for STORED in state offset-query
%7|1584699822.532|OFFSET|rdkafka#consumer-1| [thrd:main]: dsp1 [0]: no current leader for partition: (re)starting offset query timer for offset STORED
%7|1584699822.532|CONNECT|rdkafka#consumer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: coordinator query
%7|1584699822.532|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: Group "dev_test2": no broker available for coordinator query: intervaled in state query-coord

thanks

**Comment by renzhenguo** [comment]
kafka log

kafka.common.KafkaException: Wrong request type 18
	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:64)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:450)
	at kafka.network.Processor.run(SocketServer.scala:340)
	at java.lang.Thread.run(Thread.java:745)

**Comment by renzhenguo** [comment]
kafka version: 2.10-0.8.2.2

**Comment by renzhenguo** [comment]
$conf->set('api.version.request', 'false');
$conf->set('broker.version.fallback', '0.8.2.2');

Success
