### ISSUE TITLE
[6.0.0RC1] segfault in test suite

### ISSUE THREAD

**Issue by remicollet** [php-rdkafka/php-rdkafka#491]
```
TEST 32/32 [tests/topic_partition.phpt]
========DIFF========
001+ Termsig=11
001- object(RdKafka\TopicPartition)#1 (4) {
002-   ["topic"]=>
003-   string(4) "test"
004-   ["partition"]=>
005-   int(-1)
006-   ["offset"]=>
007-   int(42)
008-   ["err"]=>
009-   int(0)
010- }
011- array(3) {
012-   ["topic"]=>
013-   string(4) "test"
014-   ["partition"]=>
015-   int(-1)
016-   ["offset"]=>
017-   int(42)
018- }
019- object(RdKafka\TopicPartition)#1 (4) {
020-   ["topic"]=>
021-   string(3) "foo"
022-   ["partition"]=>
023-   int(123)
024-   ["offset"]=>
025-   int(43)
026-   ["err"]=>
027-   int(0)
028- }
========DONE========
FAIL RdKafka\TopicPartition [tests/topic_partition.phpt] 

```

**Comment by andypost** [comment]
Confirm it building PHP 8.1 for Alpinelinux on following arches armhf, s390x, aarch64 (x86*,armv7,ppc64le passing)

**EDIT** https://gitlab.alpinelinux.org/alpine/aports/-/pipelines/100272

**Comment by andypost** [comment]
Also it fails on `riscv64` and `armv7` arch https://gitlab.alpinelinux.org/alpine/aports/-/jobs/542442

**Comment by remicollet** [comment]
```
(gdb) bt
#0  zend_parse_arg_impl (arg_num=3, severity=<synthetic pointer>, error=0x7fffffff9408, spec=0x7fffffff9478, va=0x7fffffff94c0, arg=<optimized out>) at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/Zend/zend_API.c:632
#1  zend_parse_arg (arg_num=arg_num@entry=3, arg=0x7ffff72141c0, va=va@entry=0x7fffffff94c0, spec=spec@entry=0x7fffffff9478, flags=flags@entry=0) at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/Zend/zend_API.c:860
#2  0x00005555557d8963 in zend_parse_va_args (num_args=0, type_spec=<optimized out>, va=0x7fffffff94c0, flags=0) at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/Zend/zend_API.c:1035
#3  0x00005555557d8c1a in zend_parse_parameters (num_args=<optimized out>, type_spec=type_spec@entry=0x7ffff7fa03a2 "sl|l!") at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/Zend/zend_API.c:1069
#4  0x00007ffff7f9e274 in zim_RdKafka_TopicPartition___construct (execute_data=0x7ffff7214150, return_value=<optimized out>) at /dev/shm/BUILD/php-pecl-rdkafka6-6.0.0~RC1/NTS/topic_partition.c:210
#5  0x0000555555857b27 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/Zend/zend_vm_execute.h:1618
#6  execute_ex (ex=0x30) at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/Zend/zend_vm_execute.h:53521
#7  0x0000555555859c8b in zend_execute (op_array=0x7ffff728a2a0, return_value=0x0) at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/Zend/zend_vm_execute.h:57617
#8  0x00005555557d079c in zend_execute_scripts (type=type@entry=8, retval=0x7ffff729d080, retval@entry=0x0, file_count=-148815840, file_count@entry=3) at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/Zend/zend.c:1679
#9  0x000055555576da50 in php_execute_script (primary_file=<optimized out>) at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/main/main.c:2674
#10 0x000055555585bd9a in do_cli (argc=68, argv=0x555555e21240) at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/sapi/cli/php_cli.c:964
#11 0x000055555563c47e in main (argc=68, argv=0x555555e21240) at /usr/src/debug/php-7.4.26-1.fc33.remi.x86_64/sapi/cli/php_cli.c:1360

```

**Comment by remicollet** [comment]
@andypost please try with PR #492
