### ISSUE TITLE
Segmentation fault with simple Producer

### ISSUE THREAD

**Issue by bencen** [php-rdkafka/php-rdkafka#64]
- PHP version:php5.6
- librdkafka version:0.9.1
- php-rdkfaka version:php-rdkafka-0.9.1-php5

producer.php

```
$broker = 'kafka.bj.xxx.com:9092';
    $topic = '1b2de4ec923e4fe69b31dd9149921b7e__demo';
    $conf = new RdKafka\Conf();
    $conf->set('security.protocol', 'ssl');
    $conf->set('ssl.ca.location', 'ca.pem');
    $conf->set('ssl.certificate.location', 'client.pem');
    $conf->set('ssl.key.location', 'client.key');
    $rk = new RdKafka\Producer($conf);
    $rk->setLogLevel(LOG_DEBUG);
    $rk->addBrokers($broker);
    $topic = $rk->newTopic($topic);

    for ($i = 0; $i < 10; $i++) {
        $topic->produce(RD_KAFKA_PARTITION_UA, 0, "message: hello php-kafka");
    }
```

```
[root@instance-nczkiuew default]# php producer.php
Segmentation fault (core dumped)
[root@instance-nczkiuew default]# gdb php -c core.27566
GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...done.
[New LWP 27566]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `php producer.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe298778050 in ?? ()
(gdb) bt
#0  0x00007fe298778050 in ?? ()
#1  0x00007fe2a33d2c3f in engine_table_cleanup () from /usr/lib64/libcrypto.so.10
#2  0x00007fe2a33d13b6 in ?? () from /usr/lib64/libcrypto.so.10
#3  0x00007fe2a33e0a90 in sk_pop_free () from /usr/lib64/libcrypto.so.10
#4  0x00007fe2a33d138c in ENGINE_cleanup () from /usr/lib64/libcrypto.so.10
#5  0x00007fe2a30e599e in Curl_ossl_cleanup () from /usr/local/lib/libcurl.so.4
#6  0x00007fe2a30e7b52 in Curl_ssl_cleanup () from /usr/local/lib/libcurl.so.4
#7  0x00007fe2a30c7435 in curl_global_cleanup () from /usr/local/lib/libcurl.so.4
#8  0x0000000000571108 in zm_shutdown_curl (type=<optimized out>, module_number=11) at /root/lnmp/src/php-5.6.24/ext/curl/interface.c:1263
#9  0x0000000000853fd5 in module_destructor (module=0x1323220) at /root/lnmp/src/php-5.6.24/Zend/zend_API.c:2376
#10 0x000000000085af16 in i_zend_hash_bucket_delete (p=0x13231c0, ht=0xee3780 <module_registry>) at /root/lnmp/src/php-5.6.24/Zend/zend_hash.c:182
#11 zend_hash_bucket_delete (ht=0xee3780 <module_registry>, p=0x13231c0) at /root/lnmp/src/php-5.6.24/Zend/zend_hash.c:192
#12 0x000000000085b1e8 in zend_hash_graceful_reverse_destroy (ht=0xee3780 <module_registry>) at /root/lnmp/src/php-5.6.24/Zend/zend_hash.c:613
#13 0x000000000084e4d2 in zend_shutdown () at /root/lnmp/src/php-5.6.24/Zend/zend.c:836
#14 0x00000000007eccaa in php_module_shutdown () at /root/lnmp/src/php-5.6.24/main/main.c:2477
#15 0x00000000008f41c5 in main (argc=2, argv=0x12fbb60) at /root/lnmp/src/php-5.6.24/sapi/cli/php_cli.c:1393
(gdb) 
```

**Comment by arnaud-lb** [comment]
Seems related to #59
